const ailments = ['ADHD',
    'Chronic Fatigue Syndrome',
    'Gout',
    'Radiation Treatment',
    'Adenoids Removed',
    'Headaches',
    'Chronic Sinus Problems',
    'AIDS/HIV Positive',
    'Rapid Weight Gain/Loss',
    'Rheumatic Fever',
    'Alcoholism',
    'Heart Attack',
    'Heart Disease',
    'Rheumatic Heart Disease',
    'Cochlear Implant',
    'Allergies/Hay Fever',
    'Scarlet Fever',
    'Congenital Heart Defect',
    'Anaphylaxis',
    'Heart Murmur',
    'Convulsions/Seizures',
    'Anemia',
    'Shingles',
    'Cortisone Treatments',
    'Shortness of Breath',
    'Heart Surgery',
    'Heart Pacemaker',
    'Cosmetic Surgery',
    'Hemophilia',
    'Skin Rash',
    'Angina Pectoris',
    'Cough Persistent',
    'Arthritis/Rheumatism',
    'Herpes',
    'Sleep Apnea',
    'Artificial Heart Valves',
    'Cough Up Blood',
    'Hepatitis',
    'Smoking',
    'Artificial Joint (Hip/Knee)',
    'High Blood Pressure',
    "Crohn's Disease",
    'Depression',
    'Snoring',
    'Asthma',
    'Anxiety',
    'Stroke',
    'High Cholesterol',
    'Irritable Bowel Syndrome',
    'Surgical Implant',
    'Diabetes',
    'Dizziness/Fainting',
    'Jaw Pain',
    'Back Problems',
    'Drug Addiction',
    'Blood Disease',
    'Kidney Disease',
    'Swelling of Feet/Ankles',
    'Blood Transfusion',
    'Systemic Lupus Eryth',
    'Latex Allergy',
    'Emphysema/COPD',
    'Thyroid Disease',
    'Liver Disease',
    'Epilepsy',
    'Bipolar Disorder',
    'Bruises Easily',
    'Tobacco Use',
    'Tonsillitis',
    'Low Blood Pressure',
    'Cancer',
    'Mitral Valve Prolapse',
    'Fever Blisters',
    'Tonsils Removed',
    'Fibromyalgia',
    'Cerebral Palsy',
    'Multiple Sclerosis',
    'Chemotherapy',
    'Gallbladder Problems',
    'Tuberculosis',
    'Ulcerative Colitis',
    'Glaucoma',
    'Osteoporosis',
    'Psychiatric Care',
    'Venereal Disease',
    'Chronic Ear Problems',
    'Food or Drug Allergies',
    ]

    const medCondObj = {}

    ailments.map((el,i) => {
        return medCondObj[el.split(" ").join("--")]={id: i, name: el, isSelected: false}
    })

    export default medCondObj